# Generated by Django 6.0.5 on 2026-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_transcriptmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptmessage',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
