# Generated by Django 6.0.5 on 2026-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_transcriptmessage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptmessage',
            name='detected_language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
