# Generated by Django 6.0.5 on 2026-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='created_at_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
